### PR TITLE
Choropleth opacity

### PR DESCRIPTION
**Pull request by mattwigway**
Make choropleth opacity configurable.

### CODE REVIEW

**Review by trevorgerhardt — COMMENTED** [review]
This is starting to appear like we should pass the number of intended `breaks` and a color function instead of an array and an opacity value. Would there be a case where we'd want a changing opacity depending on the `classIdx`?

**Comment by mattwigway** [comment]
How about we just pass in RGBA colors?

**Comment by trevorgerhardt** [comment]
That sounds good to me 👍

**Comment by mattwigway** [comment]
@trevorgerhardt  should be good to go!

**Review by trevorgerhardt — APPROVED** [review]
👍

**Pull request merged**
